"""First-order hidden Markov model fit by Baum–Welch.

The estimator learns a small discrete HMM from a sequence of symbols and
recovers a hidden-state path with Viterbi. On a synthetic two-state corpus
drawn from a known HMM it is expected to beat chance. That check is not a
decipherment.

This module does not decipher ancient scripts. It does not read Linear A,
the Voynich manuscript, Rongorongo, the Indus script, the Phaistos disk, or
any other undeciphered text. A state path is a clustering of positions under
a first-order Markov assumption. It is not a translation, a phonetic value,
or evidence about a historical inscription.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from typing import Sequence

# Explicit disclaimer kept as data so tests and callers can surface it.
DOES_NOT_DECIPHER_ANCIENT_SCRIPTS = (
    "This first-order HMM does not decipher ancient scripts. "
    "Baum–Welch on a synthetic two-state corpus only checks that a hidden "
    "state path can be recovered better than chance when the data really "
    "were generated by a two-state HMM. It is not a reading of Linear A, "
    "Voynich, Rongorongo, Indus, Phaistos, or any other undeciphered text."
)

_LOG_FLOOR = 1e-300
_SMOOTH = 1e-3


@dataclass(frozen=True)
class SyntheticTwoStateCorpus:
    """Observations drawn from a known two-state HMM, plus the generating path.

    ``states`` is only for scoring. ``fit_baum_welch`` never reads it.
    """

    symbols: tuple[str, ...]
    states: tuple[int, ...]
    alphabet: tuple[str, ...]
    seed: int

    def __post_init__(self) -> None:
        if len(self.symbols) != len(self.states):
            raise ValueError("symbols and states must have the same length")
        if len(self.alphabet) < 2:
            raise ValueError("alphabet must contain at least two symbols")


@dataclass(frozen=True)
class HMMFit:
    """A fitted first-order HMM and its Viterbi state path.

    State indices are arbitrary. Compare paths with ``aligned_state_accuracy``,
    which tries both label flips for a two-state model.
    """

    states: tuple[int, ...]
    log_likelihood: float
    start: tuple[float, ...]
    transition: tuple[tuple[float, ...], ...]
    emission: tuple[tuple[float, ...], ...]
    alphabet: tuple[str, ...]
    n_iter: int
    restarts: int

    @property
    def n_states(self) -> int:
        return len(self.start)


def generate_two_state_corpus(
    length: int = 800,
    seed: int = 0,
    alphabet: Sequence[str] = ("A", "B", "C", "D"),
) -> SyntheticTwoStateCorpus:
    """Draw a sticky two-state symbol sequence with separated emissions.

    State 0 prefers the early alphabet symbols; state 1 prefers the later
    ones. Transitions stay in the current state most of the time so the
    hidden path is recoverable by a first-order HMM and is roughly balanced.
    """
    if length < 2:
        raise ValueError("length must be at least 2")
    symbols_alpha = tuple(alphabet)
    if len(symbols_alpha) < 2 or len(set(symbols_alpha)) != len(symbols_alpha):
        raise ValueError("alphabet must be at least two distinct symbols")
    rng = random.Random(seed)
    n_sym = len(symbols_alpha)
    # Hand-built, complementary emission rows. Not estimated from data.
    emit = [_complementary_row(n_sym, favor="early"), _complementary_row(n_sym, favor="late")]
    trans = ((0.97, 0.03), (0.04, 0.96))
    state = 0 if rng.random() < 0.5 else 1
    states: list[int] = []
    observations: list[str] = []
    for _ in range(length):
        states.append(state)
        observations.append(symbols_alpha[_sample_index(rng, emit[state])])
        state = _sample_index(rng, trans[state])
    return SyntheticTwoStateCorpus(
        symbols=tuple(observations),
        states=tuple(states),
        alphabet=symbols_alpha,
        seed=seed,
    )


def fit_baum_welch(
    symbols: Sequence[str],
    n_states: int = 2,
    *,
    n_iter: int = 40,
    restarts: int = 8,
    seed: int = 0,
    alphabet: Sequence[str] | None = None,
) -> HMMFit:
    """Fit a first-order HMM by Baum–Welch and decode with Viterbi.

    Several random restarts are run. The restart with the best observation
    log-likelihood is kept. True hidden states are not an input: this is
    unsupervised. ``n_states`` other than 2 is allowed, but the bundled
    synthetic check uses two states.
    """
    if n_states < 2:
        raise ValueError("n_states must be at least 2")
    if n_iter < 1:
        raise ValueError("n_iter must be at least 1")
    if restarts < 1:
        raise ValueError("restarts must be at least 1")
    if len(symbols) < 2:
        raise ValueError("need at least two symbols")
    alpha = tuple(alphabet) if alphabet is not None else tuple(dict.fromkeys(symbols))
    if any(symbol not in alpha for symbol in symbols):
        raise ValueError("symbol outside alphabet")
    index = {symbol: i for i, symbol in enumerate(alpha)}
    obs = [index[symbol] for symbol in symbols]
    n_sym = len(alpha)
    rng = random.Random(seed)
    best: tuple[float, list[float], list[list[float]], list[list[float]], int] | None = None
    for _restart in range(restarts):
        start = _rand_simplex(rng, n_states)
        transition = [_rand_simplex(rng, n_states) for _ in range(n_states)]
        emission = [_rand_simplex(rng, n_sym) for _ in range(n_states)]
        loglik, used = _em(obs, start, transition, emission, n_iter)
        if best is None or loglik > best[0]:
            best = (loglik, start, transition, emission, used)
    assert best is not None
    loglik, start, transition, emission, used = best
    path = viterbi(obs, start, transition, emission)
    return HMMFit(
        states=tuple(path),
        log_likelihood=loglik,
        start=tuple(start),
        transition=tuple(tuple(row) for row in transition),
        emission=tuple(tuple(row) for row in emission),
        alphabet=alpha,
        n_iter=used,
        restarts=restarts,
    )


def aligned_state_accuracy(truth: Sequence[int], predicted: Sequence[int]) -> float:
    """Fraction of positions that match after the better two-state label flip.

    HMM states have no canonical names, so both the identity map and the swap
    are scored and the higher agreement is returned. For a balanced sequence,
    labeling every position with one class scores about 0.5; that is chance.
    """
    if len(truth) != len(predicted) or not truth:
        raise ValueError("truth and predicted must be non-empty and equal length")
    if any(state not in (0, 1) for state in list(truth) + list(predicted)):
        raise ValueError("aligned_state_accuracy expects states in {0, 1}")
    same = sum(t == p for t, p in zip(truth, predicted))
    flipped = len(truth) - same
    return max(same, flipped) / len(truth)


def constant_state_baseline(truth: Sequence[int]) -> float:
    """Accuracy of the best single-label guess (majority class). Chance if balanced."""
    if not truth:
        raise ValueError("truth must be non-empty")
    ones = sum(1 for state in truth if state == 1)
    zeros = len(truth) - ones
    return max(ones, zeros) / len(truth)


def viterbi(
    obs: Sequence[int],
    start: Sequence[float],
    transition: Sequence[Sequence[float]],
    emission: Sequence[Sequence[float]],
) -> list[int]:
    """Most likely state path under a first-order HMM. ``obs`` are symbol ids."""
    t_len = len(obs)
    n_states = len(start)
    if t_len == 0:
        return []
    log_start = [_log(p) for p in start]
    log_a = [[_log(p) for p in row] for row in transition]
    log_b = [[_log(p) for p in row] for row in emission]
    neg_inf = float("-inf")
    delta = [[neg_inf] * n_states for _ in range(t_len)]
    psi = [[0] * n_states for _ in range(t_len)]
    first = obs[0]
    for i in range(n_states):
        delta[0][i] = log_start[i] + log_b[i][first]
    for t in range(1, t_len):
        symbol = obs[t]
        for j in range(n_states):
            best_score = neg_inf
            best_state = 0
            emit = log_b[j][symbol]
            for i in range(n_states):
                score = delta[t - 1][i] + log_a[i][j]
                if score > best_score:
                    best_score = score
                    best_state = i
            delta[t][j] = best_score + emit
            psi[t][j] = best_state
    last = max(range(n_states), key=lambda i: delta[t_len - 1][i])
    path = [0] * t_len
    path[-1] = last
    for t in range(t_len - 2, -1, -1):
        path[t] = psi[t + 1][path[t + 1]]
    return path


def _em(
    obs: Sequence[int],
    start: list[float],
    transition: list[list[float]],
    emission: list[list[float]],
    n_iter: int,
) -> tuple[float, int]:
    """In-place Baum–Welch. Returns final log-likelihood and iterations used."""
    prev = float("-inf")
    used = 0
    loglik = prev
    for iteration in range(n_iter):
        used = iteration + 1
        loglik, log_gamma, log_xi = _forward_backward(obs, start, transition, emission)
        _reestimate(obs, start, transition, emission, log_gamma, log_xi)
        if loglik - prev < 1e-4 and iteration > 0:
            break
        prev = loglik
    return loglik, used


def _forward_backward(
    obs: Sequence[int],
    start: Sequence[float],
    transition: Sequence[Sequence[float]],
    emission: Sequence[Sequence[float]],
) -> tuple[float, list[list[float]], list[list[list[float]]]]:
    t_len = len(obs)
    n_states = len(start)
    log_start = [_log(p) for p in start]
    log_a = [[_log(p) for p in row] for row in transition]
    log_b = [[_log(p) for p in row] for row in emission]
    log_alpha = [[0.0] * n_states for _ in range(t_len)]
    log_beta = [[0.0] * n_states for _ in range(t_len)]
    first = obs[0]
    for i in range(n_states):
        log_alpha[0][i] = log_start[i] + log_b[i][first]
    for t in range(1, t_len):
        symbol = obs[t]
        for j in range(n_states):
            terms = [log_alpha[t - 1][i] + log_a[i][j] for i in range(n_states)]
            log_alpha[t][j] = log_b[j][symbol] + _logsumexp(terms)
    loglik = _logsumexp(log_alpha[t_len - 1])
    for i in range(n_states):
        log_beta[t_len - 1][i] = 0.0
    for t in range(t_len - 2, -1, -1):
        nxt = obs[t + 1]
        for i in range(n_states):
            terms = [
                log_a[i][j] + log_b[j][nxt] + log_beta[t + 1][j] for j in range(n_states)
            ]
            log_beta[t][i] = _logsumexp(terms)
    log_gamma = [[0.0] * n_states for _ in range(t_len)]
    for t in range(t_len):
        for i in range(n_states):
            log_gamma[t][i] = log_alpha[t][i] + log_beta[t][i] - loglik
    log_xi: list[list[list[float]]] = []
    for t in range(t_len - 1):
        nxt = obs[t + 1]
        step = [[0.0] * n_states for _ in range(n_states)]
        for i in range(n_states):
            for j in range(n_states):
                step[i][j] = (
                    log_alpha[t][i] + log_a[i][j] + log_b[j][nxt] + log_beta[t + 1][j] - loglik
                )
        log_xi.append(step)
    return loglik, log_gamma, log_xi


def _reestimate(
    obs: Sequence[int],
    start: list[float],
    transition: list[list[float]],
    emission: list[list[float]],
    log_gamma: list[list[float]],
    log_xi: list[list[list[float]]],
) -> None:
    n_states = len(start)
    n_sym = len(emission[0])
    t_len = len(obs)
    for i in range(n_states):
        start[i] = math.exp(log_gamma[0][i])
    _normalize(start)
    for i in range(n_states):
        mass = 0.0
        for j in range(n_states):
            acc = _SMOOTH
            for t in range(t_len - 1):
                acc += math.exp(log_xi[t][i][j])
            transition[i][j] = acc
            mass += acc
        for j in range(n_states):
            transition[i][j] /= mass
    for i in range(n_states):
        occ = [0.0] * n_sym
        mass = 0.0
        for t, symbol in enumerate(obs):
            weight = math.exp(log_gamma[t][i])
            occ[symbol] += weight
            mass += weight
        mass += _SMOOTH * n_sym
        for k in range(n_sym):
            emission[i][k] = (occ[k] + _SMOOTH) / mass


def _complementary_row(n_sym: int, favor: str) -> tuple[float, ...]:
    raw = []
    for i in range(n_sym):
        # Early symbols are likely in one state and rare in the other.
        rank = i if favor == "early" else (n_sym - 1 - i)
        raw.append(0.55 if rank == 0 else (0.28 if rank == 1 else 0.08 / max(n_sym - 2, 1)))
    total = sum(raw)
    return tuple(value / total for value in raw)


def _sample_index(rng: random.Random, weights: Sequence[float]) -> int:
    threshold = rng.random() * sum(weights)
    acc = 0.0
    for i, weight in enumerate(weights):
        acc += weight
        if acc >= threshold:
            return i
    return len(weights) - 1


def _rand_simplex(rng: random.Random, n: int) -> list[float]:
    raw = [-math.log(max(rng.random(), _LOG_FLOOR)) for _ in range(n)]
    total = sum(raw)
    return [value / total for value in raw]


def _normalize(values: list[float]) -> None:
    total = sum(values)
    if total <= 0:
        fill = 1.0 / len(values)
        for i in range(len(values)):
            values[i] = fill
        return
    for i in range(len(values)):
        values[i] /= total


def _log(p: float) -> float:
    if p <= 0.0:
        return math.log(_LOG_FLOOR)
    return math.log(p)


def _logsumexp(terms: Sequence[float]) -> float:
    peak = max(terms)
    if peak == float("-inf"):
        return float("-inf")
    acc = 0.0
    for term in terms:
        acc += math.exp(term - peak)
    return peak + math.log(acc)
