"""Known-key Quagmire II checks against the ACA printed worked example.

Source: https://www.cryptogram.org/downloads/aca.info/ciphers/QuagmireII.pdf
The printed ciphertext is independent of this implementation. These tests
do not measure keyword recovery or a solve of an unknown historical cipher.
"""

from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path

from engine.alphabet import ALPHABET
from engine.solvers.quagmire_ii import (
    ACA_CIPHER,
    ACA_CIPHERTEXT_ALPHABET,
    ACA_CIPHERTEXT_KEYWORD,
    ACA_INDICATOR,
    ACA_INDICATOR_UNDER,
    ACA_KEY,
    ACA_MESSAGE,
    ACA_PLAIN,
    ACA_PRINTED_CIPHER,
    ACA_URL,
    quagmire_ii_alphabet,
    quagmire_ii_decrypt,
    quagmire_ii_encrypt,
    quagmire_ii_key,
    solve_quagmire_ii,
)


CERT_PATH = (
    Path(__file__).resolve().parents[1] / "engine" / "data" / "quagmire_ii_certificate.json"
)

# Transcribed from the source page, rather than generated by the encryptor.
PRINTED_MESSAGE = (
    "In the Quag Two a straight plain alphabet is run against a keyed cipher alphabet."
)
PRINTED_CIPHER = (
    "JICIC OSLYK ILFVC HEBDX CCORJ IOEWA FMWKK TXBGW HRJIB KEDBJ WZABU "
    "XWHEH UXOXC U."
)
PUBLISHED_PLAIN = "INTHEQUAGTWOASTRAIGHTPLAINALPHABETISRUNAGAINSTAKEYEDCIPHERALPHABET"
PUBLISHED_CIPHER = "".join(ch for ch in PRINTED_CIPHER if ch in ALPHABET)
PUBLISHED_CIPHERTEXT_ALPHABET = "SPRINGFEVABCDHJKLMOQTUWXYZ"


def _keys(**overrides: str) -> dict[str, str]:
    keys = {
        "ciphertext_keyword": "SPRINGFEVER",
        "indicator": "FLOWER",
        "indicator_under": "A",
    }
    keys.update(overrides)
    return keys


class QuagmireIiPublishedExampleTest(unittest.TestCase):
    def test_constants_match_the_independent_printed_example(self) -> None:
        self.assertEqual(ACA_MESSAGE, PRINTED_MESSAGE)
        self.assertEqual(ACA_PLAIN, PUBLISHED_PLAIN)
        self.assertEqual(ACA_PRINTED_CIPHER, PRINTED_CIPHER)
        self.assertEqual(ACA_CIPHER, PUBLISHED_CIPHER)
        self.assertEqual(ACA_CIPHERTEXT_KEYWORD, "SPRINGFEVER")
        self.assertEqual(ACA_INDICATOR, "FLOWER")
        self.assertEqual(ACA_INDICATOR_UNDER, "A")
        self.assertEqual(ACA_CIPHERTEXT_ALPHABET, PUBLISHED_CIPHERTEXT_ALPHABET)

    def test_ciphertext_alphabet_drops_repeated_keyword_letters(self) -> None:
        self.assertEqual(
            quagmire_ii_alphabet("SPRINGFEV(ER)"), PUBLISHED_CIPHERTEXT_ALPHABET
        )
        self.assertEqual(quagmire_ii_alphabet("springfever"), PUBLISHED_CIPHERTEXT_ALPHABET)

    def test_decrypt_recovers_the_published_plaintext(self) -> None:
        self.assertEqual(quagmire_ii_decrypt(PRINTED_CIPHER, **_keys()), PUBLISHED_PLAIN)

    def test_encrypt_matches_the_published_ciphertext(self) -> None:
        self.assertEqual(quagmire_ii_encrypt(PRINTED_MESSAGE, **_keys()), PUBLISHED_CIPHER)
        self.assertEqual(
            quagmire_ii_encrypt(PRINTED_MESSAGE, **_keys(ciphertext_keyword="SPRINGFEV(ER)")),
            PUBLISHED_CIPHER,
        )

    def test_solver_reports_known_key_metadata(self) -> None:
        result = solve_quagmire_ii(PRINTED_CIPHER, **_keys())
        self.assertEqual(result.plaintext, PUBLISHED_PLAIN)
        self.assertEqual(result.method, "quagmire-ii")
        self.assertEqual(result.key, "ct=SPRINGFEVER indicator=FLOWER under=A")
        self.assertEqual(result.key, ACA_KEY)
        self.assertEqual(result.details["mode"], "known_key")
        self.assertEqual(result.details["source_url"], ACA_URL)
        self.assertEqual(result.details["plaintext_alphabet"], ALPHABET)
        self.assertEqual(result.details["ciphertext_alphabet"], PUBLISHED_CIPHERTEXT_ALPHABET)
        self.assertEqual(result.details["period"], 6)
        self.assertEqual(result.details["letters"], len(PUBLISHED_CIPHER))

    def test_repeated_indicator_and_other_column_work_for_unpublished_text(self) -> None:
        text = "The early bird, 123!"
        keys = _keys(ciphertext_keyword="harbor", indicator="EEL", indicator_under="Y")
        cipher = quagmire_ii_encrypt(text, **keys)
        self.assertEqual(quagmire_ii_decrypt(cipher, **keys), "THEEARLYBIRD")
        self.assertNotEqual(
            cipher,
            quagmire_ii_encrypt(text, **dict(keys, indicator_under="A")),
        )
        self.assertNotEqual(
            cipher,
            quagmire_ii_encrypt(text, **dict(keys, indicator="EL")),
        )
        self.assertEqual(
            quagmire_ii_key("harbor", "eel", "y"),
            "ct=HARBOR indicator=EEL under=Y",
        )

    def test_final_short_period_is_not_padded(self) -> None:
        # The period is six; this input ends after the first three rows repeat.
        cipher = quagmire_ii_encrypt("ABCDEFGHI", **_keys())
        self.assertEqual(len(cipher), 9)
        self.assertEqual(quagmire_ii_decrypt(cipher, **_keys()), "ABCDEFGHI")


class QuagmireIiInvalidInputTest(unittest.TestCase):
    def test_rejects_empty_letter_streams_and_bad_column(self) -> None:
        for transform in (quagmire_ii_encrypt, quagmire_ii_decrypt, solve_quagmire_ii):
            for text in ("", "123 !"):
                with self.subTest(transform=transform.__name__, text=text):
                    with self.assertRaises(ValueError):
                        transform(text, **_keys())
            for overrides in (
                {"ciphertext_keyword": "123"},
                {"indicator": "!"},
                {"indicator_under": ""},
                {"indicator_under": "AB"},
            ):
                with self.subTest(transform=transform.__name__, overrides=overrides):
                    with self.assertRaises(ValueError):
                        transform("ABC", **_keys(**overrides))

    def test_rejects_non_ascii_letters(self) -> None:
        for transform in (quagmire_ii_encrypt, quagmire_ii_decrypt, solve_quagmire_ii):
            with self.subTest(transform=transform.__name__, text="caf\u00e9"):
                with self.assertRaises(ValueError):
                    transform("caf\u00e9", **_keys())
            for overrides in (
                {"ciphertext_keyword": "STRA\u00dfE"},
                {"indicator": "FLEUR\u00c9"},
                {"indicator_under": "\u00e9"},
            ):
                with self.subTest(transform=transform.__name__, overrides=overrides):
                    with self.assertRaises(ValueError):
                        transform("ABC", **_keys(**overrides))


class QuagmireIiCertificateTest(unittest.TestCase):
    def test_decrypts_certificate_and_checks_recovered_hash(self) -> None:
        cert = json.loads(CERT_PATH.read_text(encoding="utf-8"))
        self.assertEqual(cert["cipher_name"], "quagmire-ii")
        self.assertEqual(cert["name"], "quagmire-ii")
        self.assertEqual(cert["plaintext"], PUBLISHED_PLAIN)
        self.assertEqual(cert["ciphertext"], PUBLISHED_CIPHER)
        keys = cert["keys"]
        result = solve_quagmire_ii(
            cert["ciphertext"],
            ciphertext_keyword=keys["ciphertext_keyword"],
            indicator=keys["indicator"],
            indicator_under=keys["indicator_under"],
        )
        self.assertEqual(result.plaintext, PUBLISHED_PLAIN)
        self.assertEqual(result.key, cert["key"])
        self.assertEqual(keys["key"], cert["key"])
        self.assertEqual(
            hashlib.sha256(result.plaintext.encode("utf-8")).hexdigest(),
            cert["plaintext_sha256"],
        )
        self.assertEqual(cert["source_url"], ACA_URL)
        self.assertEqual(cert["message"], PRINTED_MESSAGE)
        self.assertEqual(cert["printed_ciphertext"], PRINTED_CIPHER)
        self.assertEqual(keys["ciphertext_alphabet"], PUBLISHED_CIPHERTEXT_ALPHABET)
        self.assertEqual(keys["plaintext_alphabet"], ALPHABET)
        self.assertEqual(keys["period"], 6)


if __name__ == "__main__":
    unittest.main()
